#!/usr/bin/bash

Help () {
  echo "Usage: $(basename $0) [OPTIONS]... PROJECT_NAME"
  echo "Create a C++ project with PROJECT_NAME."
  echo "  -l LIBRARY_NAME           add a library LIBRARY_NAME to the project"
  echo "  -c                        use cmake instead of make"
  exit 1
}

if [ $# -lt 1 ]; then
  Help
fi

while getopts "l:c" option; do
  case "${option}" in
    l)
      lib="${OPTARG}"
      ;;
    c)
      cmakefile=true
      ;;
    ?)
      Help
      ;;
  esac
done

shift "$(($OPTIND - 1))"
mkdir "${1}"
cd "${1}"

cp ~/.cppt/* "${PWD}"

mv template.cc "${1}.cc"
sed -i "4s/.*/MAIN = ${1}/" Makefile
sed -i "8s/.*/  * @date $(date +'%b %d %Y')/" "${1}.cc"

if [ ${lib} ]; then
  mv functions.cc "${lib}.cc"
  mv functions.h "${lib}.h"
  sed -i "8s/.*/  * @date $(date +'%b %d %Y')/" "${lib}.cc"
  sed -i "14s/.*/#include \"${lib}.h\"/" "${lib}.cc"
  sed -i "16s/.*/#include \"${lib}.h\"\n/" "${1}.cc"
  sed -i "8s/.*/  * @date $(date +'%b %d %Y')/" "${lib}.h"
  sed -i "5s/\$(MAIN).o/\$(MAIN).o ${lib}.o/" Makefile
else
  rm functions.*
fi

if [ ${cmakefile} ]; then
  sed -i "3s/.*/project(${1}/" CMakeLists.txt
  sed -i "14s/proj/${1}/" CMakeLists.txt
  sed -i "18s/proj/${1}/" CMakeLists.txt
  sed -i "19s/proj/${1}/" CMakeLists.txt
  targets="$(ls -1 *.cc *.h)"
  targets=$(echo ${targets//\./'\.'})
  sed -i "15s|.*|    ${targets}|" CMakeLists.txt
  sed -i "15s| |\n    |5g" CMakeLists.txt
  rm Makefile
else
  rm CMakeLists.txt
fi
